name: CI

on:
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add production remote to push changes
      run: git remote add production ssh://pi@starostka.tplinkdns.com:10300/~/deploy-folder/project
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.0.0
      with:
        # SSH private key
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa_github # optional:
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Run a multi-line script
      run: |
        ssh-add ~/.ssh/id_rsa_github
        git push production develop
