name: CI

on:
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: git remote add production ssh://pi@starostka.tplinkdns.com:10300/~/deploy-folder/project
    - name: Run a multi-line script
      run: git push production develop
